run:
  timeout: 5m
  tests: true
  build-tags:
    - unit

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - govet    
    - staticcheck 
    - gosimple     
    - ineffassign 
    - errcheck     
    - gocyclo 
    - gofmt        
    - revive    

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - typecheck
      text: "undefined: .*mock"

service:
  golangci-lint-version: 1.55.2
