# revive.toml — конфигурация линтера revive
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.blank-imports]      # запрещает пустые импорты
[rule.var-naming]          # проверяет наименование переменных
[rule.error-return]        # проверяет, что ошибки корректно обрабатываются
[rule.unused-parameter]    # проверяет неиспользуемые параметры функций

[rule.exported]
Disabled = true            # не требовать комментарии для экспортируемых функций/структур
[rule.package-comments]
Disabled = true            # не требовать комментарии для пакетов

